CREATE TABLE IF NOT EXISTS ad (
    ad_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , name VARCHAR NOT NULL
    , main_photo VARCHAR DEFAULT NULL
    , price DOUBLE NOT NULL
    , description VARCHAR DEFAULT NULL
);