CREATE TABLE IF NOT EXISTS ad (
    ad_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , name VARCHAR NOT NULL
    , price DOUBLE NOT NULL
    , description VARCHAR DEFAULT NULL
    , photos VARCHAR DEFAULT NULL
    , creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);